### ISSUE TITLE
Erreur de lien sur le README

### ISSUE THREAD

**Issue by Fuzuki785** [CedricGoby/newsletter-open-source#1]
Bonjour,

Le lien vers GitLab pointe sur le dépôt [GitHub](https://github.com/CedricGoby/newsletter-open-source) :
```markdown
Vous pouvez également retrouver toutes les lettres sur [GitLab](https://github.com/CedricGoby/newsletter-open-source)
```
Il en est de même sur le dépôt mirroir sur [GitLab](https://gitlab.com/CedricGoby/newsletter-open-source).

Cordialement.

**Comment by CedricGoby** [comment]
Bonjour,

Merci à vous, c'est corrigé.

Bonne journée.
